/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadorajava;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import operacao.OperacoesAvancadas;
import operacao.OperacoesBasicas;

/**
 *
 * @author Aluno
 */
public class Calculadora extends javax.swing.JFrame {

    //Invocando classes   
    OperacoesBasicas ob = new OperacoesBasicas();
    OperacoesAvancadas oa = new OperacoesAvancadas();

    //Declaração de variáveis
    double num1 = 0;
    double num2 = 0;
    double resultado = 0;
    char operador;
    boolean som = false;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVisor = new javax.swing.JTextField();
        btnNove = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSete = new javax.swing.JButton();
        btnOito = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnDois = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnQuatro = new javax.swing.JButton();
        btnUm = new javax.swing.JButton();
        btnPonto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnSomar = new javax.swing.JButton();
        btnSubtrair = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnPorcento = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnZeroZero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        listHistorico = new java.awt.List();
        btnClearHistorico = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRaiz = new javax.swing.JButton();
        btnMaisMenos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconCalc.png")).getImage());
        setResizable(false);

        txtVisor.setBackground(new java.awt.Color(153, 153, 0));
        txtVisor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtVisor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVisor.setToolTipText("");
        txtVisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtVisor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnNove.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnNove.setText("9");
        btnNove.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnNove.setBorderPainted(false);
        btnNove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoveActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("BankGothic Lt BT", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 90, 79));
        jLabel2.setText("oliveira");

        btnSete.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnSete.setText("7");
        btnSete.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnSete.setBorderPainted(false);
        btnSete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeteActionPerformed(evt);
            }
        });

        btnOito.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnOito.setText("8");
        btnOito.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnOito.setBorderPainted(false);
        btnOito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOitoActionPerformed(evt);
            }
        });

        btnCinco.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnCinco.setText("5");
        btnCinco.setToolTipText("");
        btnCinco.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnCinco.setBorderPainted(false);
        btnCinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });

        btnSeis.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnSeis.setText("6");
        btnSeis.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnSeis.setBorderPainted(false);
        btnSeis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });

        btnZero.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnZero.setText("0");
        btnZero.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnZero.setBorderPainted(false);
        btnZero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnDois.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnDois.setText("2");
        btnDois.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnDois.setBorderPainted(false);
        btnDois.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoisActionPerformed(evt);
            }
        });

        btnTres.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnTres.setText("3");
        btnTres.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnTres.setBorderPainted(false);
        btnTres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });

        btnQuatro.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnQuatro.setText("4");
        btnQuatro.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnQuatro.setBorderPainted(false);
        btnQuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuatroActionPerformed(evt);
            }
        });

        btnUm.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnUm.setText("1");
        btnUm.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnUm.setBorderPainted(false);
        btnUm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmActionPerformed(evt);
            }
        });

        btnPonto.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnPonto.setText(".");
        btnPonto.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnPonto.setBorderPainted(false);
        btnPonto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPontoActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(0, 102, 153));
        btnIgual.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnIgual.setText("=");
        btnIgual.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnIgual.setBorderPainted(false);
        btnIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnSomar.setBackground(new java.awt.Color(0, 102, 153));
        btnSomar.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnSomar.setText("+");
        btnSomar.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnSomar.setBorderPainted(false);
        btnSomar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSomar.setPreferredSize(new java.awt.Dimension(70, 70));
        btnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomarActionPerformed(evt);
            }
        });

        btnSubtrair.setBackground(new java.awt.Color(0, 102, 153));
        btnSubtrair.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnSubtrair.setText("-");
        btnSubtrair.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnSubtrair.setBorderPainted(false);
        btnSubtrair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtrairActionPerformed(evt);
            }
        });

        btnDividir.setBackground(new java.awt.Color(0, 102, 153));
        btnDividir.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnDividir.setText("/");
        btnDividir.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnDividir.setBorderPainted(false);
        btnDividir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDividir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnDividir.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnMultiplicar.setBackground(new java.awt.Color(0, 102, 153));
        btnMultiplicar.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        btnMultiplicar.setText("X");
        btnMultiplicar.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnMultiplicar.setBorderPainted(false);
        btnMultiplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnPorcento.setBackground(new java.awt.Color(0, 102, 153));
        btnPorcento.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPorcento.setText("%");
        btnPorcento.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnPorcento.setBorderPainted(false);
        btnPorcento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPorcento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentoActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 0, 0));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("AC/C");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnClear.setBorderPainted(false);
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnApagar.setBackground(new java.awt.Color(153, 0, 0));
        btnApagar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnApagar.setForeground(new java.awt.Color(255, 255, 255));
        btnApagar.setText("→");
        btnApagar.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnApagar.setBorderPainted(false);
        btnApagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnApagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnApagar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnZeroZero.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnZeroZero.setText("00");
        btnZeroZero.setToolTipText("");
        btnZeroZero.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnZeroZero.setBorderPainted(false);
        btnZeroZero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZeroZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroZeroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("BankGothic Md BT", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Histórico");

        listHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listHistorico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnClearHistorico.setBackground(new java.awt.Color(153, 0, 0));
        btnClearHistorico.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnClearHistorico.setForeground(new java.awt.Color(255, 255, 255));
        btnClearHistorico.setText("LIMPAR HISTORICO");
        btnClearHistorico.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnClearHistorico.setBorderPainted(false);
        btnClearHistorico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearHistorico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClearHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearHistoricoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("BankGothic Md BT", 1, 14)); // NOI18N
        jLabel3.setText("Calculadora");

        btnRaiz.setBackground(new java.awt.Color(0, 102, 153));
        btnRaiz.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRaiz.setText("√ ");
        btnRaiz.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnRaiz.setBorderPainted(false);
        btnRaiz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRaiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRaiz.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        btnMaisMenos.setBackground(new java.awt.Color(0, 102, 153));
        btnMaisMenos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMaisMenos.setText("+/-");
        btnMaisMenos.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnMaisMenos.setBorderPainted(false);
        btnMaisMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaisMenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMaisMenos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnMaisMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisMenosActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/oliveira.png"))); // NOI18N

        btnSom.setBackground(new java.awt.Color(0, 101, 153));
        btnSom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSom.setText("x²");
        btnSom.setToolTipText("");
        btnSom.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        btnSom.setBorderPainted(false);
        btnSom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnSete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnOito, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnNove, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnUm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnDois, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnZeroZero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPorcento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSom, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMaisMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClearHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnApagar, btnCinco, btnDividir, btnDois, btnMultiplicar, btnNove, btnOito, btnPonto, btnPorcento, btnQuatro, btnSeis, btnSete, btnSubtrair, btnTres, btnUm, btnZero});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMaisMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnOito, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNove, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDois, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnZeroZero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPorcento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(listHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Configurando botões
    private void btnOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOitoActionPerformed
        setarNumerosVisor("8");
    }//GEN-LAST:event_btnOitoActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
        setarNumerosVisor("5");
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        setarNumerosVisor("6");
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        setarNumerosVisor("0");
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoisActionPerformed
        setarNumerosVisor("2");
    }//GEN-LAST:event_btnDoisActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        setarNumerosVisor("3");
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuatroActionPerformed
        setarNumerosVisor("4");
    }//GEN-LAST:event_btnQuatroActionPerformed

    private void btnUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmActionPerformed
        setarNumerosVisor("1");
    }//GEN-LAST:event_btnUmActionPerformed

    private void btnPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPontoActionPerformed
        //Configurando botão ponto
        if (txtVisor.getText().equals("") || txtVisor.getText().equals("00")) {
            txtVisor.setText("0.");
        } else {
            String valor = txtVisor.getText();
            valor = valor + ".";
            txtVisor.setText(valor);
        }
    }//GEN-LAST:event_btnPontoActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        //Configurando ação botão igual
        pegarNum2();
        calculos(operador);

        //Concatena calculo para Histórico
        String concatenar = num1 + " " + operador + " " + num2 + " = "
                + txtVisor.getText();

        listHistorico.add(concatenar);
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomarActionPerformed
        pegarNum1();
        operador = '+';
    }//GEN-LAST:event_btnSomarActionPerformed

    private void btnSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtrairActionPerformed
        pegarNum1();
operador = '-';
    }//GEN-LAST:event_btnSubtrairActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        pegarNum1();
 operador = '/';
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        num1 = 0;
        txtVisor.setText("0");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        String valor = txtVisor.getText();

        //Tratamento de erro.
        if (valor.equals("")) {
            java.awt.Toolkit.getDefaultToolkit().beep();
            txtVisor.setText("0");
        } else {
            StringBuilder w = new StringBuilder(valor);
            valor = String.valueOf(w.deleteCharAt(valor.length() - 1));
            txtVisor.setText(valor);
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnZeroZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroZeroActionPerformed
        if (txtVisor.getText().equals("")) {
            setarNumerosVisor("0");
        } else {
            setarNumerosVisor("00");
        }
    }//GEN-LAST:event_btnZeroZeroActionPerformed

    private void btnPorcentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentoActionPerformed
        pegarNum2();

        if (operador == '+') {
            oa.porcentagemMais(num1, num2);
        }
        if (operador == '-') {
            oa.porcentagemMenos(num1, num2);
        }
        if (operador == '*') {
            oa.porcentagemMultiplo(num1, num2);
        }
        if (operador == '/') {
            oa.porcentagemMultiplo(num1, num2);
        }

        //Concatena calculo para Histórico
        String concatenar = num1 + " " + operador + " " + num2 + "% = "
                + Double.toString(oa.getResultado());

        txtVisor.setText(Double.toString(oa.getResultado()));
        listHistorico.add(concatenar);
    }//GEN-LAST:event_btnPorcentoActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        pegarNum1();
 operador = '*';
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeteActionPerformed
        setarNumerosVisor("7");
    }//GEN-LAST:event_btnSeteActionPerformed

    private void btnNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoveActionPerformed
        setarNumerosVisor("9");
    }//GEN-LAST:event_btnNoveActionPerformed

    private void btnClearHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearHistoricoActionPerformed
        listHistorico.removeAll();
    }//GEN-LAST:event_btnClearHistoricoActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        pegarNum1();
oa.raiz(num1);

        //Concatena calculo para Histórico
        String concatenar = "√" + num1 + " = "
                + Double.toString(oa.getResultado());

        txtVisor.setText(Double.toString(oa.getResultado()));
        listHistorico.add(concatenar);
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnMaisMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisMenosActionPerformed
        pegarNum1();
        ob.maisMenos(num1);

        txtVisor.setText(Double.toString(ob.getResultado()));
    }//GEN-LAST:event_btnMaisMenosActionPerformed

    private void btnSomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomActionPerformed
        pegarNum1();
        oa.potencia(num1);
        
        //Concatenar para historico
        String concatena = num1 + "²" + " = " +
                Double.toString(oa.getResultado());
        txtVisor.setText(Double.toString(oa.getResultado()));
        listHistorico.add(concatena);
    }//GEN-LAST:event_btnSomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearHistorico;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnDois;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMaisMenos;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnNove;
    private javax.swing.JButton btnOito;
    private javax.swing.JButton btnPonto;
    private javax.swing.JButton btnPorcento;
    private javax.swing.JButton btnQuatro;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSete;
    private javax.swing.JButton btnSom;
    private javax.swing.JButton btnSomar;
    private javax.swing.JButton btnSubtrair;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUm;
    private javax.swing.JButton btnZero;
    private javax.swing.JButton btnZeroZero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.List listHistorico;
    private javax.swing.JTextField txtVisor;
    // End of variables declaration//GEN-END:variables

    //Metodo para setar número equivalentes dos botões
    public void setarNumerosVisor(String numero) {
        if ("0".equals(txtVisor.getText())
                || "00".equals(txtVisor.getText())) {
            txtVisor.setText("");
        }
        String valor = txtVisor.getText();
        valor = valor + numero;
        txtVisor.setText(valor);
    }

    //Metodo para pegar primeiro valor
    public void pegarNum1() {
        num1 = Double.parseDouble(txtVisor.getText());
        txtVisor.setText("");
    }

    //Metodo para pegar segundo valor
    public void pegarNum2() {
        num2 = Double.parseDouble(txtVisor.getText());
        txtVisor.setText("");
    }

    //Metodo para realizar os calculos
    public void calculos(char operador) {

        if (operador == '+') {
            ob.somar(num1, num2);
        }

        if (operador == '-') {
            ob.subtrair(num1, num2);
        }

        if (operador == '/') {
            ob.dividir(num1, num2);
        }
        
        if (operador == '*'){
            ob.multiplicar(num1, num2);
        }
        

        txtVisor.setText(Double.toString(ob.getResultado()));
    }
    
}